### ISSUE TITLE
Activate ZEROCOPY for TX without loading a BPF?

### ISSUE THREAD

**Issue by alasterrr** [xdp-project/xdp-project#100]
Hi all. I was wondering, is it possible to benefit from the ZEROCOPY feature for data transmission without having to attach a bpf to the interface? I was trying but seems like zerocopy does not activate if I don't attach a BPF filter to the interface. To make it work I had to attach a filter with XDP_PASS.

NOTE: I am using XDP for data transmission only (no RX).

**Comment by magnus-karlsson** [comment]
It depends on what NIC you use. On Intel NICs, you need to attach an XDP program (that you do not use) in order for the extra Tx queues to be created that AF_XDP zero-copy needs. These queues are unfortunately not created up front. If so, this would not have been a problem. On other NICs, this might not be necessary if they create the extra Tx queues up front.
