### ISSUE TITLE
Investigate if XDP can be used for TSN

### ISSUE THREAD

**Issue by netoptimizer** [xdp-project/xdp-project#2]
Investigate if XDP can be used for improving latency for [TSN](https://en.wikipedia.org/wiki/Time-Sensitive_Networking) (Time-Sensitive Networking)

The latency offered by the Linux kernel network stack to userspace socket delivery is generally too high for TSN requirements.

The task is to prototype and measure the latency achievable via AF_XDP sockets.

**Comment by netoptimizer** [comment]
Document for TSN: [areas/arm64/xdp_for_tsn.org](https://github.com/xdp-project/xdp-project/blob/master/areas/arm64/xdp_for_tsn.org)

added in commit d8c22ed83374df

**Comment by netoptimizer** [comment]
This TSN work looks related to https://open62541.org/

And their [report/presentation](https://open62541.org/material/Performance%20measurements%20open62541%20OPC%20UA%20TSN%20on%20x86%20I210%20Linux.pdf) that mention they want to look into using XDP/AF_XDP to lower latency.

**Comment by apalos** [comment]
We've already started working on that. Check https://github.com/muvarov/ipxdp
Although this is mostly patchwork for now, it uses AF_XDP and opc-ua(via open6241) over lwip.
This can obviously be done a lot better, but this is an easy way of proving AF_XDP can offer freatly reduced latency. 

We are trying to prepare a demo for the upcoming Linaro Connect (BKK 19) on that. I'll post the links once we prepare them

**Comment by apalos** [comment]
Doing another test to measure stack latency[1] only showed an average of ~1500ns
Depending on the application needs flushing XDP to user-space more often (instead of every NAPI completion) might be needed.

[1] By stack latency we refer to the time needed for AF_XDP to read the packet from memory and flush it to user-space. No driver processing/irq processing included
