### ISSUE TITLE
The meaning of `Drivers supporting XDP`

### ISSUE THREAD

**Issue by ChenLingPeng** [xdp-project/xdp-project#23]
Doc in https://github.com/xdp-project/xdp-project/blob/master/areas/drivers/README.org said that veth support XDP, but in my test, it can only load bpf prog in generic mode, not driver mode.

**Comment by tohojo** [comment]
Lingpeng Chen <notifications@github.com> writes:

> Doc in
> https://github.com/xdp-project/xdp-project/blob/master/areas/drivers/README.org
> said that veth support XDP, but in my test, it can only load bpf prog
> in generic mode, not driver mode.

On what kernel version? Support in native mode is quite new...

**Comment by ChenLingPeng** [comment]
> Lingpeng Chen <notifications@github.com> writes:
> Doc in https://github.com/xdp-project/xdp-project/blob/master/areas/drivers/README.org said that veth support XDP, but in my test, it can only load bpf prog in generic mode, not driver mode.
> On what kernel version? Support in native mode is quite new...

```
# uname -a
Linux node-00 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
# ethtool -i vh1
driver: veth
version: 1.0
firmware-version:
expansion-rom-version:
bus-info:
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

**Comment by ChenLingPeng** [comment]
Is there a way to detect if the interface could load xdp in driver mode without actually load a xdp prog?

**Comment by tohojo** [comment]
Lingpeng Chen <notifications@github.com> writes:

>> Lingpeng Chen <notifications@github.com> writes:
>> Doc in https://github.com/xdp-project/xdp-project/blob/master/areas/drivers/README.org said that veth support XDP, but in my test, it can only load bpf prog in generic mode, not driver mode.
>> On what kernel version? Support in native mode is quite new...
>
> ```
> # uname -a
> Linux node-00 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC
> 2019 x86_64 x86_64 x86_64 GNU/Linux

Yeah, you'll need a newer kernel. Think native XDP support for veth was
added in 4.18 or 4.19...

**Comment by tohojo** [comment]
Lingpeng Chen <notifications@github.com> writes:

> Is there a way to detect if the interface could load xdp in driver
> mode without actually load a xdp prog?

Not currently. We are planning to add one, though; see
https://github.com/xdp-project/xdp-project/blob/master/xdp-project.org#xdp-feature-flags

**Comment by ChenLingPeng** [comment]
> Lingpeng Chen <notifications@github.com> writes:
> > Lingpeng Chen ***@***.***> writes: > Doc in https://github.com/xdp-project/xdp-project/blob/master/areas/drivers/README.org said that veth support XDP, but in my test, it can only load bpf prog in generic mode, not driver mode. > On what kernel version? Support in native mode is quite new... ``` # uname -a Linux node-00 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> Yeah, you'll need a newer kernel. Think native XDP support for veth was added in 4.18 or 4.19...

just tested that 4.18 not support this. should I use ubuntu 19.04 to test this feature?

```
# uname -a
Linux Forrest-3 4.18.0-1018-azure #18~18.04.1-Ubuntu SMP Tue May 7 18:09:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tohojo** [comment]
Lingpeng Chen <notifications@github.com> writes:

>> Lingpeng Chen <notifications@github.com> writes:
>> > Lingpeng Chen ***@***.***> writes: > Doc in https://github.com/xdp-project/xdp-project/blob/master/areas/drivers/README.org said that veth support XDP, but in my test, it can only load bpf prog in generic mode, not driver mode. > On what kernel version? Support in native mode is quite new... ``` # uname -a Linux node-00 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
>> Yeah, you'll need a newer kernel. Think native XDP support for veth was added in 4.18 or 4.19...
>
> just tested that 4.18 not support this. should I use ubuntu 19.04 to
> test this feature?

Ah, sorry, I misremembered... The veth support wasn't added until
4.19... If you're upgrading anyway you may want to go all the way to
4.20 as that added ethtool statistics support to veth as well...

**Comment by tohojo** [comment]
Closing this issue. Please re-open if you think your question wasn't answered...
