### ISSUE TITLE
Meta-Data and latency measurements for AF-XDP

### ISSUE THREAD

**Issue by Bresenham** [xdp-project/xdp-project#33]
I wanted to try your example for AF-XDP latency measurement: https://github.com/xdp-project/xdp-project/blob/master/areas/arm64/xdp_for_tsn.org
As far as I understood correctly, you are inserting a `bpf_ktime_get_ns()` timestamp into the meta-data of a packet and later compare that value with another timestamp in userspace.

I tried to adapt your example code for my XDP-program like this:

```
    const unsigned long long kstamp = bpf_ktime_get_ns();

    void *data, *data_end;
    unsigned long long *data_meta;

    if(bpf_xdp_adjust_meta(ctx, -(int)( sizeof(kstamp)  )) < 0) {
        bpf_printk("Failed to adjust meta\n");
        return XDP_PASS;
    }

    int index = ctx->rx_queue_index;

    data = (void*)(unsigned long)ctx->data;
    data_end = (void*)(unsigned long)ctx->data_end;
    data_meta = (void*)(unsigned long)ctx->data_meta;

    if(data_meta + 1 > data) {
        return XDP_PASS;
    }

    *data_meta = kstamp;
```

But I always get `Failed to adjust meta\n` in my bpf-output via `cat /sys/kernel/debug/tracing/trace_pipe`. So it seems like the device driver of my network interface does not support adding meta-data (according to your comment in https://github.com/xdp-project/net-next/blob/master/samples/bpf/xdp2skb_meta_kern.c)?

I then thought of another way. I overwrite part of the payload of a packet (just for measurement purposes) like this:

```
void *data, *data_end;

data = (void*)(unsigned long)ctx->data;
data_end = (void*)(unsigned long)ctx->data_end;

void *pos = data;
struct ethhdr *eth = (struct ethhdr*)(pos);

if(eth + sizeof(struct ethhdr) <= data_end) {

    if(bpf_ntohs(eth->h_proto) == ETH_P_IP) {
        struct iphdr *iph = (struct iphdr*)(pos + sizeof(struct ethhdr));

        if(iph + sizeof(struct iphdr) <= data_end) {

            if(iph->protocol == IPPROTO_UDP) {
                const __u16 iph_sz_in_bytes = iph->ihl * 4;

                if(iph + iph_sz_in_bytes <= data_end) {
                    struct udphdr *udh = (struct udphdr*)(pos + sizeof(struct ethhdr) + iph_sz_in_bytes);
    
                    if(udh + sizeof(struct udphdr) + RTP_HDR_MIN_SIZE + sizeof(unsigned long long) <= data_end) {

                        const unsigned long long kstamp = bpf_ktime_get_ns();
                        unsigned long long *kstamp_ptr = (unsigned long long*)(pos + sizeof(struct ethhdr) + iph_sz_in_bytes + sizeof(struct udphdr) + RTP_HDR_MIN_SIZE + sizeof(unsigned long long));
                        *kstamp_ptr = kstamp;
                    }
                    ....
                
                }
            }
        }
    }
}
```

And then later in user-space, compare this value with:

```
uint8_t *pkt_meta = (uint8_t*)(pkt + sizeof(struct ethhdr) + iph_sz_in_bytes + sizeof(struct udphdr) + RTP_HDR_MIN_SIZE + sizeof(unsigned long long));
unsigned long long *kstamp = (unsigned long long*)pkt_meta;

struct timespec t;
if(clock_gettime(CLOCK_MONOTONIC, &t) < 0) {
    fprintf(stderr, "Failed to obtain `clock_gettime` timestamp: %s!\n", strerror(errno));
    return false;
}

const double tdiff = ( ((unsigned long long)(t.tv_sec * 1000000000) + t.tv_nsec) - *kstamp ) / 1000.0;
xsk->stats.latency_us += tdiff;
```

But I don't think this solution is right because you guys measured a latency of just over 3µs here: https://github.com/xdp-project/xdp-project/issues/2

but I am measuring an average latency of `98.1µs` for around 135.000 pps (no packet loss).

I also did `xsk_ring_cons__peek(&xsk->rx, 1, &idx_rx);` in user-space to already start processing packets even though only 1 packet is available (if I use a bulk-size of 128 packets I get up to `~220µs`).

I am working on a 24-Core Xeon server.

What is wrong here?

**Comment by tohojo** [comment]
@apalos care to comment?

**Comment by apalos** [comment]
@Bresenham i've never tried to use bpf_ktime_get_ns(). What i did was hack up the driver, so once i was in the NAPI poller i manually added a kernel timestamp with ktime_get_ns(). 
I manually inserted the timestamp in the drvier xdp meta-data with something like
`
ts = ktime_get_ns();
xdp.data_meta = xdp.data - sizeof(ts);
memcpy(xdp.data_meta, &ts, sizeof(ts));`

I have no idea why bpf_ktime_get_ns() fails in your case. What driver are you using to test this

**Comment by Bresenham** [comment]
`bpf_ktime_get_ns` doesn't fail, but `bpf_xdp_adjust_meta` does. Because of that, I just wrote the timestamp into the packet-payload (for now, I am only checking for packetloss etc. so the actual content is not of great interest atm).

> What i did was hack up the driver

Okay, I don't want to go the route to hack the driver of my NIC

**Comment by apalos** [comment]
> `bpf_ktime_get_ns` doesn't fail, but `bpf_xdp_adjust_meta` does. Because of that, I just wrote the timestamp into the packet-payload (for now, I am only checking for packetloss etc. so the actual content is not of great interest atm).
> 
> Qeole explained in his answer to this post: https://stackoverflow.com/questions/60487925/af-xdp-how-do-i-get-ctx-data-meta-from-kernel-into-user-space why `bpf_xdp_adjust_meta` can fail.
> 
> > What i did was hack up the driver
> 
> Okay, I don't want to go the route to hack the driver of my NIC

What driver are you using?
The point is to get as detailed measuring as possible. 
Adding the timestamp when you enter the NAPI poll and passing it down to user-space will ensure that you get a correct value for NAPI -> flush to userspace. 
This is not accurate enough, but it's the best solution you have if you card does not support hardware timestamping.

The ideal way to measure this is use phc2sys and sync your clocks. The pick up the hardware timestamp and compare it with your user-space one

**Comment by Bresenham** [comment]
So you think that around `90µs` can't be a valid time (not even in the same ballpark)? What do you mean with `NAPI poll`? I am not aware of "polling the NAPI" to be honest. Driver is `driver: mlx5_core
version: 5.0-0`

**Comment by netoptimizer** [comment]
@Bresenham have you noticed: https://github.com/xdp-project/xdp-project/blob/master/areas/latency/softirq_net_latency.bt

It is not what you want, but we can learn something from the script at use it for your purpose.
The tool catch latency issues when the system hardirq tries to raise softirq, but softirq is processed too late. There is also [napi_monitor.bt](https://github.com/xdp-project/xdp-project/blob/master/areas/latency/napi_monitor.bt), which is closer to what I think you need.

@apalos modified the kernel driver to get the timestamp when NAPi starts, but with above trick that is not needed. Because you can use ```tracepoint:irq:softirq_raise``` and instead store the NAPI start timestamp in a per-CPU global map, which you can read from XDP context (this only works because softirq/NAPI blocks others from running). In XDP context you can even get a new timestamp and store both timestamps in ```metadata``` or packet-area, and then again when you see the packet in userspace via AF_XDP.

**Comment by Bresenham** [comment]
> So you think that around 90µs can't be a valid time (not even in the same ballpark)?
Is this statement correct?

**Comment by apalos** [comment]
@netoptimizer This is a nice idea as long as he can identify the NAPI spercific softirq
@Bresenham : We've measured < 90us using the kernel network stack, so 90 for XDP seems unlikely keeping in mind it bypasses a bunch of layers in the kernel and does not alocate SKBs
