### ISSUE TITLE
How to catch packets sent by XDP user program

### ISSUE THREAD

**Issue by tuilagio** [xdp-project/xdp-project#34]
I am working on  project that requires intercepting and manipulating packets sent by XDP userspace-program (like an indepent controller/sampler). I tried attach a bpf program on egress with tc but the XDP-packets got through without tc-program notice. I am digging in XDP kernel code, however didn't find anything jet.

tc program<br>
``` c
// sudo tc filter add dev ens13 egress bpf da obj layercoop.o sec tx
SEC("tx")
int track_tx(struct __sk_buff *skb)
{
    __u64 t2 = bpf_ktime_get_ns();
    void *data_end = (void *)(long)skb->data_end;
    void *data = (void *)(long)skb->data;
    bpf_custom_printk("\n__________send length %d\n", data_end-data); 
    return TC_ACT_OK;
}
```

**Comment by tohojo** [comment]
You mean you have an application that uses AF_XDP to send packets, and you want to intercept them in the kernel "on the way out"?

Not sure if there's a way to do that; the whole point of AF_XDP is that it bypasses the kernel...

@magnus-karlsson or @bjoto should know...

**Comment by tuilagio** [comment]
@tohojo Yes. As far as I know there was a discussion about XDP on the egress by the developer of XDP.
The reason for that is I am building a sampler-controller that does the QC, so I need to know as exact as possible when the packets leave the system.

**Comment by tohojo** [comment]
tuilagio <notifications@github.com> writes:

> @tohojo Yes. As far as I know there was a discussion about XDP on the egress by the developer of XDP.
> The reason for that is I am building a sampler-controller that does the QC, so I need to know as exact as possible when the packets leave the system.

Hmm, right, the egress hook might be an approximation for that, but I'm
not sure if that is going to apply to AF_XDP either...
