### ISSUE TITLE
AF_XDP Mac Layer Frame Format Type

### ISSUE THREAD

**Issue by janrueth** [xdp-project/xdp-project#35]
Hi,

not sure if this is the right place to ask this question but I was wondering about the "correct" or "recommended" way of programmatically establishing the mac layer frame format of `AF_XDP` sockets.

`Libpcap` or other `AF_PACKET` sockets can retrieve the mac layer format via an `ioctl` on their fd using `SIOCGIFHWADDR` and investigate `ifr_hwaddr.sa_family` (see `man 7 netdevice`).

Using an `AF_XDP` socket, such an `ioctl` fails on Kernel 5.4 (`Operation not supported`)
While I can certainly open an `AF_PACKET` socket and do the `ioctl` and close the socket again, I'm unsure if the result would always indicate the same frame type that I would receive through `AF_XDP`.

Best
 Jan

**Comment by bjoto** [comment]
Jan,

AF_XDP does not support any ioctls, and currently there are not plans for adding it. To obtain the L2 format, as you also describe, is via netdevice(7) (AF_INET/AF_PACKET) or via rtnetlink(3).

Cheers,
Björn

**Comment by janrueth** [comment]
Hi Björn,

thanks for the fast reply and the hint to netlink.
I'll be closing this issue and for anybody digging this up:

Netlink exposes this via `RTM_GETLINK` and `ifi_type` in `struct ifinfomsg`.
Libnl seems to also provide functions to deal with translations to string `nl_llproto2str` and back `nl_str2llproto`

Thanks
 Jan
