### ISSUE TITLE
pkt capture issue on xdp hook

### ISSUE THREAD

**Issue by sachints123** [xdp-project/xdp-project#56]
Hi All,

I am observing one strange behavior on my setup.

I have a pkt generator(third party hardware) connected to one linux server "A" where my xdp programs runs.
pktgen----->server A.------>server B

I have xdp ebpf program attached to "A" ingress interface and modifying ip header and redirecting to egress interface.
But I am not able to capture incoming pkt on ingress interface unless i start tcpdump on it. I am not understanding how is it dependent on tcpdump  ? Am i missing something in configuring ebpf program on xdp ?

Kindly advise me.

Sachin

**Comment by tohojo** [comment]
sachints123 <notifications@github.com> writes:

> Hi All,
>
> I am observing one strange behavior on my setup.
>
> I have a pkt generator(third party hardware) connected to one linux server "A" where my xdp programs runs.
> pktgen----->server A.------>server B
>
> I have xdp ebpf program attached to "A" ingress interface and
> modifying ip header and redirecting to egress interface.
>
> But I am not able to capture incoming pkt on ingress interface unless
> i start tcpdump on it. I am not understanding how is it dependent on
> tcpdump  ? Am i missing something in configuring ebpf program on xdp ?

You mean that your XDP program doesn't see any packets until you start
tcpdump? By default, tcpdump will put the interface into promiscuous
mode, so maybe the packets do not have your hardware's MAC address as
their destination, and the hardware is filtering them by default?

**Comment by sachints123** [comment]
> sachints123 <notifications@github.com> writes:
> Hi All, I am observing one strange behavior on my setup. I have a pkt generator(third party hardware) connected to one linux server "A" where my xdp programs runs. pktgen----->server A.------>server B I have xdp ebpf program attached to "A" ingress interface and modifying ip header and redirecting to egress interface. But I am not able to capture incoming pkt on ingress interface unless i start tcpdump on it. I am not understanding how is it dependent on tcpdump ? Am i missing something in configuring ebpf program on xdp ?
> You mean that your XDP program doesn't see any packets until you start tcpdump? By default, tcpdump will put the interface into promiscuous mode, so maybe the packets do not have your hardware's MAC address as their destination, and the hardware is filtering them by default?

Yes, I can't see any packets until I start tcpdump.
Yes, you are right, as the packets are generated with some default MAC address, its getting filtered. I enabled promisc mode on ingress and its working fine without tcpdump. 
Thanks for your inputs.

**Comment by sachints123** [comment]
> sachints123 <notifications@github.com> writes:
> Hi All, I am observing one strange behavior on my setup. I have a pkt generator(third party hardware) connected to one linux server "A" where my xdp programs runs. pktgen----->server A.------>server B I have xdp ebpf program attached to "A" ingress interface and modifying ip header and redirecting to egress interface. But I am not able to capture incoming pkt on ingress interface unless i start tcpdump on it. I am not understanding how is it dependent on tcpdump ? Am i missing something in configuring ebpf program on xdp ?
> You mean that your XDP program doesn't see any packets until you start tcpdump? By default, tcpdump will put the interface into promiscuous mode, so maybe the packets do not have your hardware's MAC address as their destination, and the hardware is filtering them by default?

@tohojo I am redirecting pkt using bpf_clone_redirect on tc hook and capturing same pkt on xdp hook of redirected interface and doing XDP_PASS. Will this pass the packet to network stack of that interface and will the packets ethernet header gets updated based on the interfaces mac address  or keeps the original mac?

**Comment by tohojo** [comment]
sachints123 <notifications@github.com> writes:

>> sachints123 <notifications@github.com> writes:
>> Hi All, I am observing one strange behavior on my setup. I have a pkt generator(third party hardware) connected to one linux server "A" where my xdp programs runs. pktgen----->server A.------>server B I have xdp ebpf program attached to "A" ingress interface and modifying ip header and redirecting to egress interface. But I am not able to capture incoming pkt on ingress interface unless i start tcpdump on it. I am not understanding how is it dependent on tcpdump ? Am i missing something in configuring ebpf program on xdp ?
>> You mean that your XDP program doesn't see any packets until you start tcpdump? By default, tcpdump will put the interface into promiscuous mode, so maybe the packets do not have your hardware's MAC address as their destination, and the hardware is filtering them by default?
>
> @tohojo I am redirecting pkt using bpf_clone_redirect on tc hook and
> capturing same pkt on xdp hook of redirected interface and doing
> XDP_PASS.

Right (I assume you're using veth devices for this, right?). Note that
this doesn't really give you any performance benefit from XDP, as the
packets are already processed by the stack on the TC hook side.

> Will this pass the packet to network stack of that interface

Yup

> and will the packets ethernet header gets updated based on the
> interfaces mac address  or keeps the original mac?

Unless you modify the MAC in your BPF program(s) it should keep the
original one...

**Comment by sachints123** [comment]
> sachints123 <notifications@github.com> writes:
> > sachints123 ***@***.***> writes: > Hi All, I am observing one strange behavior on my setup. I have a pkt generator(third party hardware) connected to one linux server "A" where my xdp programs runs. pktgen----->server A.------>server B I have xdp ebpf program attached to "A" ingress interface and modifying ip header and redirecting to egress interface. But I am not able to capture incoming pkt on ingress interface unless i start tcpdump on it. I am not understanding how is it dependent on tcpdump ? Am i missing something in configuring ebpf program on xdp ? > You mean that your XDP program doesn't see any packets until you start tcpdump? By default, tcpdump will put the interface into promiscuous mode, so maybe the packets do not have your hardware's MAC address as their destination, and the hardware is filtering them by default? @tohojo I am redirecting pkt using bpf_clone_redirect on tc hook and capturing same pkt on xdp hook of redirected interface and doing XDP_PASS.
> Right (I assume you're using veth devices for this, right?). Note that this doesn't really give you any performance benefit from XDP, as the packets are already processed by the stack on the TC hook side.
Sachin>> No this time I am using real interface, a mini PC with one NIC port and two usb-to-ethernet adapters. Each connected to disjoint routers.
> Will this pass the packet to network stack of that interface
> Yup
> and will the packets ethernet header gets updated based on the interfaces mac address or keeps the original mac?
> Unless you modify the MAC in your BPF program(s) it should keep the original one...
Sachin>> Oh ok, i was under the assumption that XDP_PASS will pass back to kernel path and MAC will be updated accordingly. So, this is the reason I was seeing drops when the packets are redirected to routers. 
Is there any doc or link which i can refer for packet traversal when ebpf hooks are used?

**Comment by tohojo** [comment]
sachints123 <notifications@github.com> writes:

>> Right (I assume you're using veth devices for this, right?). Note
>> that this doesn't really give you any performance benefit from XDP,
>> as the packets are already processed by the stack on the TC hook
>> side.
>
> Sachin>> No this time I am using real interface, a mini PC with one
> NIC port and two usb-to-ethernet adapters. Each connected to disjoint
> routers.

OK, so what do you mean by "capturing same pkt on xdp hook of redirected
interface and doing XDP_PASS"? That is after it has been through the
routers, or?

>> Will this pass the packet to network stack of that interface
>> Yup
>> and will the packets ethernet header gets updated based on the interfaces mac address or keeps the original mac?
>> Unless you modify the MAC in your BPF program(s) it should keep the original one...
> Sachin>> Oh ok, i was under the assumption that XDP_PASS will pass
> back to kernel path and MAC will be updated accordingly. So, this is
> the reason I was seeing drops when the packets are redirected to
> routers.

An XDP program that returns XDP_PASS without modifying the packet is
equivalent to not having any XDP program at all. So any modification
will have to be done in the XDP program; what do you mean, "updated
accordingly"?

> Is there any doc or link which i can refer for packet traversal when
> ebpf hooks are used?

Not really, that I'm aware of :(

**Comment by sachints123** [comment]
> sachints123 <notifications@github.com> writes:
> > Right (I assume you're using veth devices for this, right?). Note > that this doesn't really give you any performance benefit from XDP, > as the packets are already processed by the stack on the TC hook > side. Sachin>> No this time I am using real interface, a mini PC with one NIC port and two usb-to-ethernet adapters. Each connected to disjoint routers.
> OK, so what do you mean by "capturing same pkt on xdp hook of redirected interface and doing XDP_PASS"? That is after it has been through the routers, or?

For better understanding, let me explain what I did.  As mentioned, on mini PC I have 3 interfaces, one is input which receives IP packets from pkt gen. Other two are connected to two routers. I am adding a custom L4 header on input ingress XDP and cloning it on input ingress TC hook and redirecting it to two out interfaces which are connected to routers. As the dst MAC addresses were not matching, pkts are being dropped on routers. So, with my wrong assumption, I added xdp_pass hooks on out interfaces(on mini PC) to capture modified IP pkts and XDP_PASS to stack. Still packets are getting dropped on routers. Your previous comment clarified this, that dst mac will not be changed during XDP_PASS.
So, in order to route pkts successfully through routers, I need to manually modify pkts mac before sending it to routers, am I right? or Is there any way that I can achieve this?

> > Will this pass the packet to network stack of that interface > Yup > and will the packets ethernet header gets updated based on the interfaces mac address or keeps the original mac? > Unless you modify the MAC in your BPF program(s) it should keep the original one... Sachin>> Oh ok, i was under the assumption that XDP_PASS will pass back to kernel path and MAC will be updated accordingly. So, this is the reason I was seeing drops when the packets are redirected to routers.
> An XDP program that returns XDP_PASS without modifying the packet is equivalent to not having any XDP program at all. So any modification will have to be done in the XDP program; what do you mean, "updated accordingly"?
I thought XDP_PASS will return the packet to network stack  and gets processed like normal path (without ebpf hooks, checking MAC, routing, iptables etc).
> Is there any doc or link which i can refer for packet traversal when ebpf hooks are used?
> Not really, that I'm aware of :(
oh ok :(

**Comment by tohojo** [comment]
sachints123 <notifications@github.com> writes:

>> sachints123 <notifications@github.com> writes:
>> > Right (I assume you're using veth devices for this, right?). Note > that this doesn't really give you any performance benefit from XDP, > as the packets are already processed by the stack on the TC hook > side. Sachin>> No this time I am using real interface, a mini PC with one NIC port and two usb-to-ethernet adapters. Each connected to disjoint routers.
>> OK, so what do you mean by "capturing same pkt on xdp hook of redirected interface and doing XDP_PASS"? That is after it has been through the routers, or?
>
> For better understanding, let me explain what I did.  As mentioned, on
> mini PC I have 3 interfaces, one is input which receives IP packets
> from pkt gen. Other two are connected to two routers. I am adding a
> custom L4 header on input ingress XDP and cloning it on input ingress
> TC hook and redirecting it to two out interfaces which are connected
> to routers. As the dst MAC addresses were not matching, pkts are being
> dropped on routers. So, with my wrong assumption, I added xdp_pass
> hooks on out interfaces(on mini PC) to capture modified IP pkts and
> XDP_PASS to stack. Still packets are getting dropped on routers. Your
> previous comment clarified this, that dst mac will not be changed
> during XDP_PASS.

Yes, and also XDP doesn't work on egress, only on ingress; so attaching
programs to your egress interface doesn't do anything in this setup.

> So, in order to route pkts successfully through routers, I need to
> manually modify pkts mac before sending it to routers, am I right? or
> Is there any way that I can achieve this?

You can just modify the packets in the TC hook before redirecting?

**Comment by sachints123** [comment]
> sachints123 <notifications@github.com> writes:
> > sachints123 ***@***.***> writes: > > Right (I assume you're using veth devices for this, right?). Note > that this doesn't really give you any performance benefit from XDP, > as the packets are already processed by the stack on the TC hook > side. Sachin>> No this time I am using real interface, a mini PC with one NIC port and two usb-to-ethernet adapters. Each connected to disjoint routers. > OK, so what do you mean by "capturing same pkt on xdp hook of redirected interface and doing XDP_PASS"? That is after it has been through the routers, or? For better understanding, let me explain what I did. As mentioned, on mini PC I have 3 interfaces, one is input which receives IP packets from pkt gen. Other two are connected to two routers. I am adding a custom L4 header on input ingress XDP and cloning it on input ingress TC hook and redirecting it to two out interfaces which are connected to routers. As the dst MAC addresses were not matching, pkts are being dropped on routers. So, with my wrong assumption, I added xdp_pass hooks on out interfaces(on mini PC) to capture modified IP pkts and XDP_PASS to stack. Still packets are getting dropped on routers. Your previous comment clarified this, that dst mac will not be changed during XDP_PASS.
> Yes, and also XDP doesn't work on egress, only on ingress; so attaching programs to your egress interface doesn't do anything in this setup.

@tohojo Thank you very much for the clarifications. 

> So, in order to route pkts successfully through routers, I need to manually modify pkts mac before sending it to routers, am I right? or Is there any way that I can achieve this?
> You can just modify the packets in the TC hook before redirecting?

Ok, I think I can do this at XDP also while adding custom L4 header. Right?

**Comment by tohojo** [comment]
sachints123 <notifications@github.com> writes:

>> sachints123 <notifications@github.com> writes:
>> > sachints123 ***@***.***> writes: > > Right (I assume you're using veth devices for this, right?). Note > that this doesn't really give you any performance benefit from XDP, > as the packets are already processed by the stack on the TC hook > side. Sachin>> No this time I am using real interface, a mini PC with one NIC port and two usb-to-ethernet adapters. Each connected to disjoint routers. > OK, so what do you mean by "capturing same pkt on xdp hook of redirected interface and doing XDP_PASS"? That is after it has been through the routers, or? For better understanding, let me explain what I did. As mentioned, on mini PC I have 3 interfaces, one is input which receives IP packets from pkt gen. Other two are connected to two routers. I am adding a custom L4 header on input ingress XDP and cloning it on input ingress TC hook and redirecting it to two out interfaces which are connected to routers. As the dst MAC addresses were not matching, pkts are being dropped on routers. So, with my wrong assumption, I added xdp_pass hooks on out interfaces(on mini PC) to capture modified IP pkts and XDP_PASS to stack. Still packets are getting dropped on routers. Your previous comment clarified this, that dst mac will not be changed during XDP_PASS.
>> Yes, and also XDP doesn't work on egress, only on ingress; so attaching programs to your egress interface doesn't do anything in this setup.
>
> @tohojo Thank you very much for the clarifications.

You're welcome :)

>> So, in order to route pkts successfully through routers, I need to manually modify pkts mac before sending it to routers, am I right? or Is there any way that I can achieve this?
>> You can just modify the packets in the TC hook before redirecting?
>
> Ok, I think I can do this at XDP also while adding custom L4 header.
> Right?

Well depends - your XDP program is pre-clone, so you can't have
different MACs on each copy of the packet. If you don't need that then
sure, you can just modify it in XDP; otherwise you'll have to do it on a
TC egress hook on each egress interface...

There's work in progress to make it possible to do what you're trying to
do entirely in XDP, BTW: https://lore.kernel.org/bpf/20210120022514.2862872-1-liuhangbin@gmail.com/

**Comment by tohojo** [comment]
sachints123 <notifications@github.com> writes:

>>  There's work in progress to make it possible to do what you're trying to do entirely in XDP, BTW: https://lore.kernel.org/bpf/20210120022514.2862872-1-liuhangbin@gmail.com/
>
> Oh this is great, reduces lot of work. I hope this also gives
> flexibility of modifying MACs for different interfaces like what I am
> trying to achieve.

It will - you can attach a program in the redirect map that will modify
the (copy of) the packet after the redirect happens...

**Comment by sachints123** [comment]
> sachints123 <notifications@github.com> writes:
> > There's work in progress to make it possible to do what you're trying to do entirely in XDP, BTW: ***@***.***/ Oh this is great, reduces lot of work. I hope this also gives flexibility of modifying MACs for different interfaces like what I am trying to achieve.
> It will - you can attach a program in the redirect map that will modify the (copy of) the packet after the redirect happens...

Ok Great! Thanks for your time :)

**Comment by tohojo** [comment]
You're welcome :)
