### ISSUE TITLE
Client does not accept SYN-ACK packet, retransmits SYN packet instead

### ISSUE THREAD

**Issue by tbwLcFm5uXcAeQ** [xdp-project/xdp-project#81]
Greetings,

I've a basic AF_XDP server and I'm trying to implement the TCP handshake, but for some reason the client program does not accept the SYN-ACK packet.

I've validated that the packet arrives at the client using a simple AF_PACKET client, but when using `connect(3)`, wireshark shows that instead of sending an ACK response, the SYN packet is retransmitted.

Any clue why this might be happening?

**Comment by tohojo** [comment]
Checksum mismatch?
