### ISSUE TITLE
Accurately timestamping packets in ebpf/xdp

### ISSUE THREAD

**Issue by bmo-at** [xdp-project/xdp-project#84]
Hi, 

we have been looking for a way to capture packets with XDP for tracing purposes.
As part of our effort, we would like to get an accurate (nanosecond precision) unix epoch timestamp for each packet.
So far, we have not been able to identify a good way to achieve this.
Best we can tell, it isn't actually possible, since in an ebpf program we can only access the time since boot in nanoseconds (with the help of  `bpf_ktime_get_boot_ns()`).
But that doesn't really help us at all, because even though we can use a map to communicate this kernel uptime to the userspace program, we can't accurately compute the difference since the kernel uptime is only available in 100th-of-a-second precision via `/proc/uptime` or `/proc/stat` -> `btime`.
In the documentation we found a [reference](https://github.com/xdp-project/xdp-project/blob/master/xdp-project.org#metadata-available-to-programs) to the fact that package meta data context could be extended to include other information, including the timestamp, but this does not seem to have been done yet.

Is there anyone that has had a similar problem and maybe found a solution or can anyone advise how to achieve this?
Are there any plans to implement the additional meta data in the near future?

**Comment by tohojo** [comment]
You can absolutely get the time with nanosecond precision from userspace:
```sh
$ cat >time.c <<EOF
#include <time.h>
#include <stdio.h>

int main() {
  struct timespec ts = {};
  int ret;

  ret = clock_gettime(CLOCK_BOOTTIME, &ts);
  printf("%llu.%09llu\n", ts.tv_sec, ts.tv_nsec);
  return ret;
}
EOF
$ gcc time.c
$ ./a.out
91897.676979335
```

As for the metadata format, this was merged for 6.3, with hardware timestamps being one of the supported pieces of metadata (still very limited driver support, though). See https://lore.kernel.org/r/20230119221536.3349901-1-sdf@google.com

**Comment by bmo-at** [comment]
Genuinely: Thank you for making me feel dumb on using `CLOCK_BOOTTIME`. Was researching this with a coworker yesterday, we kept finding posts and articles using `CLOCK_MONOTONIC` and `CLOCK_REALTIME`, but not `CLOCK_BOOTTIME`. We were thinking we can't possibly be the only people experiencing this, and of course we aren't. Should have had a good look at `man clock_gettime`. Sometimes a good man page read pays of more than 100 Stackoverflow posts.

Thank you also for the update on the metadata format, I will note it down in a comment. But as we are developing this for a debian based system it will likely take a while before this change makes its way to our systems.
Again, thanks for the quick and helpful answer!

**Comment by tohojo** [comment]
Haha, you're welcome! :)

And yeah, will probably be a while still until the hardware metadata
thing is generally usable...
