### ISSUE TITLE
Wrong EFI Loader Signature 

### ISSUE THREAD

**Issue by Atishya-AJ** [xdp-project/xdp-project#97]
I have implemented the egress XDP Patch on kernel 5.4.274 and complied it successfully but got an issue at time of booting .
When I selected the option for 5.4.274 version in which I have done this modification , got this Window

![Screenshot (139)](https://github.com/xdp-project/xdp-project/assets/61741992/75e80668-77f3-423f-97e2-58fb28e14732)

and then this

![Screenshot (141)](https://github.com/xdp-project/xdp-project/assets/61741992/c6d1b520-3c27-4bac-816c-4b59f0d98ad7)

how to fix this ?

**Comment by tohojo** [comment]
Sorry, we can't help you with out of tree kernel issues
